#!/bin/bash
#
# Configuration for shell colors
#
# vim: set ft=sh

# Global `ls` color file /etc/DIR_COLORS
if [ -f "/etc/DIR_COLORS" ]; then
    eval $(dircolors -b /etc/DIR_COLORS)
fi

# Custom `ls` color file : ~/.dircolors
if [ -f "$HOME/.dircolors" ]; then
    eval $(dircolors -b ~/.dircolors)
fi

# Colors
NORMAL="\[\033[0m\]"
BLACK="\[\e[0;30m\]"
WHITE="\[\e[0;37m\]"
RED="\[\e[0;31m\]"
GREEN="\[\e[0;32m\]"
YELLOW="\[\e[0;33m\]"
BLUE="\[\e[0;34m\]"
PURPLE="\[\e[0;35m\]"
CYAN="\[\e[0;36m\]"
BBLACK="\[\e[1;30m\]"
BWHITE="\[\e[1;37m\]"
BRED="\[\e[1;31m\]"
BGREEN="\[\e[1;32m\]"
BYELLOW="\[\e[1;33m\]"
BBLUE="\[\e[1;34m\]"
BPURPLE="\[\e[1;35m\]"
BCYAN="\[\e[1;36m\]"

if $use_personnal_prompt; then
    # Prompt format
    if $use_git_prompt; then
        PS1=${BBLUE}'\u'${NORMAL}${BYELLOW}@${NORMAL}${BRED}'\h'${NORMAL}${BBLUE}:${NORMAL}${BGREEN}'\w'${NORMAL}${BPURPLE}'$(__git_ps1 "|%s")'"${NORMAL}${BBLUE} "'\$'"${NORMAL} "
    else
        PS1=${BBLUE}'\u'${NORMAL}${BYELLOW}@${NORMAL}${BRED}'\h'${NORMAL}${BBLUE}:${NORMAL}${BGREEN}'\w'"${NORMAL}${BBLUE} "'\$'"${NORMAL} "
    fi
    PS2="${BLUE}>${NORMAL} "
fi
