#!/bin/bash
#
# Configuration for shell profile.
#
# vim: set ft=sh

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Prefer french and use UTF-8
export LC_ALL="fr_FR.UTF8"
export LANG="fr_FR"

# Add private bin directory if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
