#!/bin/bash
#
# Configuration for shell profile.
#
# vim: set ft=sh

# Autocorrect typos in path names when using `cd`
shopt -s cdspell

# Prefer US English and use UTF-8
# export LC_ALL="fr_FR.UTF-8"
# export LANG="fr_FR"

# Configure terminal correctly for Vim
if [ -e /usr/share/terminfo/x/xterm-256color ]; then
    export TERM='xterm-256color'
else
    export TERM='xterm-color'
fi

# Add private bin directory if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
