#!/bin/bash
#
# Configuration for shell colors
#
# vim: set ft=sh

# Global `ls` color file /etc/DIR_COLORS
if [ -f "/etc/DIR_COLORS" ]; then
    eval $(dircolors -b /etc/DIR_COLORS)
fi

# Custom `ls` color file : ~/.dircolors
if [ -f "$HOME/.dircolors" ]; then
    eval $(dircolors -b ~/.dircolors)
fi

# Colors
NORMAL="\[\033[0m\]"
BLACK="\[\e[1;30m\]"
WHITE="\[\e[1;37m\]"
RED="\[\e[1;31m\]"
GREEN="\[\e[1;32m\]"
YELLOW="\[\e[1;33m\]"
BLUE="\[\e[1;34m\]"
PURPLE="\[\e[1;35m\]"
CYAN="\[\e[1;36m\]"

# Prompt format
PS1=${BLUE}'\u'${NORMAL}${YELLOW}@${NORMAL}${RED}'\h'${NORMAL}${YELLOW}${NORMAL}${YELLOW}${NORMAL}${BLUE}:${NORMAL}${GREEN}'\w'${NORMAL}${PURPLE}'$(__git_ps1 "|%s")'"${NORMAL}${BLUE} "'\$'"${NORMAL} "
PS2="${BLUE}>${NORMAL} "
