""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Sections:
"     General
"     VIM user interface
"     Syntax
"     Colors and fonts
"     Files and backups
"     Text, buffers, tab and indent related
"     Editing mappings
"     Plugins customization
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" General
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Leader map
let mapleader = ","

" Use the plugin pathogen to include other plugins
call pathogen#infect()
call pathogen#helptags()

" Size of the history
set history=700

" Read again the current file if it has been edited from outside
set autoread

" Enable filetype
filetype plugin on
filetype indent on

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" VIM user interface
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Shorten some message of vim
set shortmess=aTWI

" Always show the status line
set laststatus=2

" Do not show the used mode (for powerline)
set noshowmode

" Title is the name of the current file
set title

" Buffer become hidden when abandoned
set hidden

" Set 13 lines to the cursor - when moving vertically using j/k
" 13 for the luck
set scrolloff=13

" Active the wild menu
set wildmenu

" Use <TAB> to show the wildmenu
set wildchar=<TAB>

" Set the mode of the completion
set wildmode=list:longest

" Ignore compiled files
set wildignore=*.o,*.pyc,*~,*/.git/*,*/.svn/*

" Always show current position
set ruler

" Show line number
set number

" Height of the command line
set cmdheight=1

" Specifies backspace
set backspace=eol,start,indent

" Add wrapping in normal and visual mode
set whichwrap+=<,>,l,h

" Don't redraw while executing macros
set lazyredraw

" Disable mouse
set mouse=
set mousehide

" Fix for terminal enabling ALT key mappings
if !has("gui_running")
    let s:c = "a"
    while s:c <= "z"
        execute "set <A-" . s:c . ">=\e" . s:c
        execute "imap \e" . s:c . " <A-" . s:c . ">"
        let s:c = nr2char(1 + char2nr(s:c))
    endwhile
    set timeout ttimeoutlen=50
endif

" Enable magic for regular exp
set magic

" Ignore case when searching
set ignorecase

" Try to be smart about cases when searching
set smartcase

" Higlight search result
set hlsearch

" When search is canceled, return to the old position
set incsearch

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Syntax
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Enable syntax detection
syntax enable

" Show matching brackets
set showmatch
set matchtime=2

" Tags (go up directories and collect "tags" files)
set tags=./tags;/

" Default complete function
set omnifunc=syntaxcomplete#Complete

" Set style of the completion
set completeopt=menu,longest

" Expand path with local files
set path+=/usr/local/include

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Colors and fonts
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Set the background
set background=dark

" Determine number of colors
let s:nb_colors = system('tput colors')
execute 'set t_Co=' . s:nb_colors

" Colorscheme
let g:solarized_termcolors=s:nb_colors
colorscheme solarized

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Files and backups
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Remove backup files
set nobackup
set nowritebackup

" Do not use swap file
set noswapfile

" Use UTF-8 charset
set encoding=utf-8

" Choose the good file encoding
set fileencodings=ucs-bom,utf-8,default,latin1

" Choose the good file format
set fileformats=unix,dos

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Text, buffers, tab and related
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Indentation option
set autoindent
set smartindent
set shiftwidth=2

" Tabulation option
set expandtab
set smarttab
set softtabstop=2
set tabstop=4

" Replace indentation, eol and other non visible char
set list listchars=tab:▸\ ,trail:⋅,extends:❯,precedes:❮,eol:¤
set showbreak=↪

" Virtual edit
" set virtualedit=all

" Line break on 100 characters
" set linebreak
" set textwidth=100

" Return to last edit position when opening files (You want this!)
if has('autocmd')
autocmd BufReadPost *
            \ if line("'\"") > 0 && line("'\"") <= line("$") |
            \   exe "normal! g`\"" |
            \ endif
endif

" Open quickfix window automatically after a make command
" if there are errors
if has('autocmd')
    autocmd QuickFixCmdPost [^l]* nested cwindow
    autocmd QuickFixCmdPost    l* nested lwindow
endif

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Editing mappings
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Disable arrows key
nnoremap <up>    <nop>
nnoremap <down>  <nop>
nnoremap <left>  <nop>
nnoremap <right> <nop>

" Shortcut to save
nnoremap <silent> <leader>w :write<cr>

" Close current file
nmap <silent> <leader>q :quit<cr>

" Run ls in shell
nmap <silent> <leader>ls :!ls<cr>

" Edit/Source vimrc
nmap <silent> <leader>co :edit $MYVIMRC<cr>
nmap <silent> <leader>so :source $MYVIMRC<cr>

" Switch CWD to the directory of the current buffer
nmap <silent> <leader>cd :cd %:p:h<cr>:pwd<cr>

" Disable highlight
nmap <silent> <leader><cr> :set nohlsearch<cr>

" Quick search and replace
nnoremap <leader>s :%s/\v<<C-r><C-w>>//gI<left><left><left>
" TODO enable this in visual mode

" Replace the char under the cursor by another on the current line (usefull
" when working on x, y, z line
nnoremap <leader>l vy:s/<C-r>"//gI<left><left><left>
vnoremap <leader>l y:s/<C-r>"//gI<left><left><left>

" Transform Y to y$
nmap Y y$

" Indentation with visual mode keep the selection
vmap > >gv
vmap < <gv

" Move rapidly between opened windows
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Move rapidly between opened tabs
nnoremap <silent> <C-t> :tabnew<cr>
nnoremap <silent> <S-t> :tabclose<cr>
nnoremap <silent> <C-D> :tabclose<cr>
" Little hack with XTerm
nnoremap <silent> [27;5;9 :tabnext<cr>
nnoremap <silent> [27;6;9 :tabprevious<cr>
nnoremap <silent> <S-l> :tabnext<cr>
nnoremap <silent> <S-h> :tabprevious<cr>

" Remap vim 0 to first non-blank char
nmap 0 ^

" Quick indenting
nmap <tab> ==

" Quick make command
nmap <silent> <leader>m :make<cr>

" Exchange ' `
nnoremap ' `
nnoremap ` '

" Move a line of text using Alt+[jk]
nnoremap <silent> <M-j> mz:move .+1<cr>`z
nnoremap <silent> <M-k> mz:move .-2<cr>`z
inoremap <silent> <M-j> <esc>:move .+1<cr>gi
inoremap <silent> <M-k> <esc>:move .-2<cr>gi
vnoremap <silent> <M-j> :move '>+1<cr>gvgv
vnoremap <silent> <M-k> :move '<-2<cr>gvgv

" Stay at the same position when using = in visual mode
vnoremap = =gv<esc>

" Close current buffer
nmap <silent> <leader>bd :bdelete<cr>

" Use make in vim
nmap <silent> <leader>cw :cwindow<cr>
nmap <silent> <leader>cn :cn<cr>
nmap <silent> <leader>cp :cp<cr>

" Very annoying thing
imap ê <C-v>ê

""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Plugins customization
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" NERDTree
nnoremap <silent> <f2> :NERDTreeToggle<cr>

" Ctrl+P
let g:ctrlp_map = '<c-p>'
let g:ctrlp_cmd = 'CtrlP'
let g:ctrlp_match_window = 'top,order:ttb,min:1,max:10'
let g:ctrlp_working_path_mode = 'ra'
let g:ctrlp_use_caching = 1
let g:ctrlp_custom_ignore = {
            \ 'dir':  '\v[\/]\.(git|hg|svn)$',
            \ 'file': '\v\.(exe|so|dll|pyc|o)$',
            \ 'link': 'SOME_BAD_SYMBOLIC_LINKS',
            \ }
let g:ctrlp_max_files = 1000
let g:ctrlp_max_depth = 40
let g:ctrlp_user_command = {
            \ 'types': {
            \ 1: ['.git', 'cd %s && git ls-files'],
            \ },
            \ 'fallback': 'find %s -type f'
            \ }
let g:ctrlp_open_new_file = 'r'
let g:ctrlp_open_multiple_files = '3vjr'

" LanguageTool
let g:languagetool_jar='~/logiciel/LanguageTool-2.2/languagetool-commandline.jar'
