#!/bin/zsh
#
# Profile used by zsh
#
# vim: set ft=zsh

# Prefer french and use UTF-8
export LC_ALL="fr_FR.UTF8"
export LANG="fr_FR"
export EDITOR="vim"

# Configure terminal correctly for Vim
if [ -n "$DISPLAY" -a "$TERM" = "xterm" ]; then
    export TERM='xterm-256color'
fi

# Colors
if [ -x /usr/bin/dircolors ]; then
    if [ -r ~/.dircolors ] ; then
        eval $(dircolors -b ~/.dircolors)
    elif [ -r /etc/dir_colors ] ; then
        eval $(dircolors -b /etc/dir_colors)
    else
        eval $(dircolors)
    fi
fi

