#!/bin/zsh
#
# Configuration of the inputs
#
# vim: set ft=zsh

# Use the vim configuration for the key shortcuts
bindkey -v

# Fix some bugs with Home, End, Del keys
bindkey 'OH' beginning-of-line                 # Home
bindkey 'OF' end-of-line                       # End
bindkey "^[[3~" delete-char                      # Delete
bindkey '[2~' overwrite-mode                   # Insert
bindkey '[5~' history-search-backward          # PgUp
bindkey '[6~' history-search-forward           # PgDn
bindkey '[A' history-search-backward           # Up
bindkey '[B' history-search-forward            # Down

bindkey '\e[1~' beginning-of-line
bindkey '\e[4~' end-of-line
bindkey '\e[7~' beginning-of-line
bindkey '\e[8~' end-of-line
bindkey '\eOH' beginning-of-line
bindkey '\eOF' end-of-line
bindkey '\e[H' beginning-of-line
bindkey '\e[F' end-of-line
