#!/bin/zsh
#
# Main configuration for zsh
#
# vim: set ft=zsh

ZSH_CONF_DIR="$HOME/.zsh"
#
# Option
#

# BIP
setopt beep
setopt hist_beep
setopt list_beep

# Show the return code if different of 0
# setopt print_exit_value

# Ask confirmation for rm *
unsetopt rm_star_silent

# Active the command correction
# setopt correct
# setopt correct-all

# Remove useless joker instead of getting an error
setopt nullglob

# Complete directly with the first choice in the proposed list
# setopt menu_complete

# Show directly the list of proposition without waiting a second <TAB>
# unsetopt list_ambigous

# Clear the last / of an autocompletion if the user types space after
setopt auto_remove_slash

# Don't complete hidden files
# unsetopt glob_dots

# Use correctly symbolic link
setopt chase_links

# If the user begins by a ! to do a history completion,
# the command isn't execute immediatly but is written in the prompt
setopt hist_verify

# If the command is invalid but is a directory,
# use cd directory instead
setopt auto_cd

# After a cd, put the old path on the stack
setopt auto_pushd

# Ignore double is the stack
setopt pushd_ignore_dups

# Don't show the stack after a pushd or a popd
setopt pushd_silent

# If pushd is use without args -> pushd $HOME
setopt pushd_to_home

# Don't run all background jobs at a lower priority
unsetopt bg_nice

# Don't Check the status of background job before exiting the shell
unsetopt check_jobs
unsetopt hup

#
# Make less more friendly for non-text input files
if [ -x /usr/bin/lesspipe ]; then
    export "LESSOPEN=| /usr/bin/lesspipe %s"
    export "LESSCLOSE=/usr/bin/lesspipe %s %s"
fi

# History option
source $ZSH_CONF_DIR/zsh_history

# Auto completion
source $ZSH_CONF_DIR/zsh_completion

# Configuration for shell aliases.
source $ZSH_CONF_DIR/zsh_aliases

# Configuration for shell profile
source $ZSH_CONF_DIR/zsh_profile

# Prompt
source $ZSH_CONF_DIR/zsh_prompt
