#!/bin/zsh
#
# Profile used by zsh
#
# vim: set ft=zsh

# Configure terminal correctly for Vim
if [ -e /usr/share/terminfo/x/xterm-256color ]; then
    export TERM='xterm-256color'
else
    export TERM='xterm-color'
fi

# Colors
if [ -x /usr/bin/dircolors ]; then
    if [ -r ~/.dircolors ] ; then
        eval $(dircolors -b ~/.dircolors)
    elif [ -r /etc/dir_colors ] ; then
        eval $(dircolors -b /etc/dir_colors)
    else
        eval $(dircolors)
    fi
fi

