#!/bin/bash
#
# Configuration for shell aliases.
#
# vim: set ft=sh

# Security aliases
alias free="free -m"
alias df="df -h"
alias rm="rm -vi"
alias cp="cp -vi"
alias mv="mv -vi"
alias glxgears="glxgears -printfps"

# Package managing
alias install="sudo apt-get install"
alias remove="sudo apt-get remove"
alias autoremove="sudo apt-get autoremove"
alias update="sudo apt-get update"
alias upgrade="sudo apt-get upgrade --show-upgraded"
alias clean="sudo apt-get clean"
alias search="sudo dpkg -l"

# Navigation
alias ..="cd ../"
alias ...="cd ../../"
alias ....="cd ../../../"
alias dw="cd ~/Downloads"
alias doc="cd ~/Documents"
alias img="cd ~/Images"
alias mkdir="mkdir -p"
alias uua="sudo apt-get update -y && sudo apt-get upgrade -y && sudo apt-get autoremove -y"
alias susu="sudo -s"

# Quick display
alias grep="grep --color=auto"
alias tree="tree -Csu"
alias ls="ls -X --color=auto"
alias la="ls -a"
alias ll="ls -l"
alias lla="ls -la"
alias lr="ls -r"

# Git aliases
alias gc="git clone"
alias gr="git reset"
alias ga="git add"
alias gaa="git add ."

# One-key commands
alias h="cd ~"
alias d="cd ~/Desktop"
alias p="cd ~/Projects"
alias c="clear"
alias v="vim"
alias g="gvim -f --remote-silent"
alias l="ls"
alias t="tree"

# Google Chrome
alias google-chrome="google-chrome --enable-plugins"

# Setup completion for aliases
#
# install -> apt-get install
make-completion-wrapper _apt_get _install apt-get install
complete -o filenames -F _install install
